Don't use sops (#138)
This commit removes the secret handling from the flux setup.

Since the sops binary is now baked into the flux image, originally I was thinking it would be good to check in secrets and then let flux handle the decrytion with a generator in the .flux.yaml command. Unfortunately this wasn't a well documented part of flux and never really worked properly. There were lots of messages like this in the logs:

```sh
Error: verifying changes: failed to verify changes: the image for container "api" in resource "api:deployment/tracker-api" should be "gcr.io/track-compliance/api:master-48db84c", but is "gcr.io/track-compliance/api:update-frontend-deps-862b39e"
```

This sort of thing was mysterious and blocked deployments from happening, making our continuous deployment not very continuous.

What's happening here is biting the bullet and seeding the cluster with secrets when flux is getting set up. The GKE overlay will then just assume the secrets exist.